var countries = [
	{ 'cn': 'Afghanistan', 'cc': 'AF', 'dc': '+93' },
	{ 'cn': 'Albania', 'cc': 'AL', 'dc': '+355' },
	{ 'cn': 'Algeria', 'cc': 'DZ', 'dc': '+213' },
	{ 'cn': 'American Samoa', 'cc': 'AS', 'dc': '+1' },
	{ 'cn': 'Andorra', 'cc': 'AD', 'dc': '+376' },
	{ 'cn': 'Angola', 'cc': 'AO', 'dc': '+244' },
	{ 'cn': 'Anguilla', 'cc': 'AI', 'dc': '+1' },
	{ 'cn': 'Antarctica', 'cc': 'AQ', 'dc': '+672' },
	{ 'cn': 'Antigua and Barbuda', 'cc': 'AG', 'dc': '+1' },
	{ 'cn': 'Argentina', 'cc': 'AR', 'dc': '+54' },
	{ 'cn': 'Armenia', 'cc': 'AM', 'dc': '+374' },
	{ 'cn': 'Aruba', 'cc': 'AW', 'dc': '+297' },
	{ 'cn': 'Australia', 'cc': 'AU', 'dc': '+61' },
	{ 'cn': 'Austria', 'cc': 'AT', 'dc': '+43' },
	{ 'cn': 'Azerbaijan', 'cc': 'AZ', 'dc': '+994' },
	{ 'cn': 'Bahamas', 'cc': 'BS', 'dc': '+1' },
	{ 'cn': 'Bahrain', 'cc': 'BH', 'dc': '+973' },
	{ 'cn': 'Bangladesh', 'cc': 'BD', 'dc': '+880' },
	{ 'cn': 'Barbados', 'cc': 'BB', 'dc': '+1' },
	{ 'cn': 'Belarus', 'cc': 'BY', 'dc': '+375' },
	{ 'cn': 'Belgium', 'cc': 'BE', 'dc': '+32' },
	{ 'cn': 'Belize', 'cc': 'BZ', 'dc': '+501' },
	{ 'cn': 'Benin', 'cc': 'BJ', 'dc': '+229' },
	{ 'cn': 'Bermuda', 'cc': 'BM', 'dc': '+1' },
	{ 'cn': 'Bhutan', 'cc': 'BT', 'dc': '+975' },
	{ 'cn': 'Bolivia', 'cc': 'BO', 'dc': '+591' },
	{ 'cn': 'Bosnia and Herzegovina', 'cc': 'BA', 'dc': '+387' },
	{ 'cn': 'Botswana', 'cc': 'BW', 'dc': '+267' },
	{ 'cn': 'Brazil', 'cc': 'BR', 'dc': '+55' },
	{ 'cn': 'British Indian Ocean Territory', 'cc': 'IO', 'dc': '+246' },
	{ 'cn': 'British Virgin Islands', 'cc': 'VG', 'dc': '+1' },
	{ 'cn': 'Brunei', 'cc': 'BN', 'dc': '+673' },
	{ 'cn': 'Bulgaria', 'cc': 'BG', 'dc': '+359' },
	{ 'cn': 'Burkina Faso', 'cc': 'BF', 'dc': '+226' },
	{ 'cn': 'Burundi', 'cc': 'BI', 'dc': '+257' },
	{ 'cn': 'Cambodia', 'cc': 'KH', 'dc': '+855' },
	{ 'cn': 'Cameroon', 'cc': 'CM', 'dc': '+237' },
	{ 'cn': 'Canada', 'cc': 'CA', 'dc': '+1' },
	{ 'cn': 'Cape Verde', 'cc': 'CV', 'dc': '+238' },
	{ 'cn': 'Cayman Islands', 'cc': 'KY', 'dc': '+1' },
	{ 'cn': 'Central African Republic', 'cc': 'CF', 'dc': '+236' },
	{ 'cn': 'Chad', 'cc': 'TD', 'dc': '+235' },
	{ 'cn': 'Chile', 'cc': 'CL', 'dc': '+56' },
	{ 'cn': 'China', 'cc': 'CN', 'dc': '+86' },
	{ 'cn': 'Christmas Island', 'cc': 'CX', 'dc': '+61' },
	{ 'cn': 'Cocos Islands', 'cc': 'CC', 'dc': '+61' },
	{ 'cn': 'Colombia', 'cc': 'CO', 'dc': '+57' },
	{ 'cn': 'Comoros', 'cc': 'KM', 'dc': '+269' },
	{ 'cn': 'Cook Islands', 'cc': 'CK', 'dc': '+682' },
	{ 'cn': 'Costa Rica', 'cc': 'CR', 'dc': '+506' },
	{ 'cn': 'Croatia', 'cc': 'HR', 'dc': '+385' },
	{ 'cn': 'Cuba', 'cc': 'CU', 'dc': '+53' },
	{ 'cn': 'Curacao', 'cc': 'CW', 'dc': '+599' },
	{ 'cn': 'Cyprus', 'cc': 'CY', 'dc': '+357' },
	{ 'cn': 'Czech Republic', 'cc': 'CZ', 'dc': '+420' },
	{ 'cn': 'Democratic Republic of the Congo', 'cc': 'CD', 'dc': '+243' },
	{ 'cn': 'Denmark', 'cc': 'DK', 'dc': '+45' },
	{ 'cn': 'Djibouti', 'cc': 'DJ', 'dc': '+253' },
	{ 'cn': 'Dominica', 'cc': 'DM', 'dc': '+1' },
	{ 'cn': 'Dominican Republic', 'cc': 'DO', 'dc': '+1' },
	{ 'cn': 'East Timor', 'cc': 'TL', 'dc': '+670' },
	{ 'cn': 'Ecuador', 'cc': 'EC', 'dc': '+593' },
	{ 'cn': 'Egypt', 'cc': 'EG', 'dc': '+20' }, 
	{ 'cn': 'El Salvador', 'cc': 'SV', 'dc': '+503' },
	{ 'cn': 'Equatorial Guinea', 'cc': 'GQ', 'dc': '+240' },
	{ 'cn': 'Eritrea', 'cc': 'ER', 'dc': '+291' },
	{ 'cn': 'Estonia', 'cc': 'EE', 'dc': '+372' },
	{ 'cn': 'Ethiopia', 'cc': 'ET', 'dc': '+251' },
	{ 'cn': 'Falkland Islands', 'cc': 'FK', 'dc': '+500' },
	{ 'cn': 'Faroe Islands', 'cc': 'FO', 'dc': '+298' },
	{ 'cn': 'Fiji', 'cc': 'FJ', 'dc': '+679' },
	{ 'cn': 'Finland', 'cc': 'FI', 'dc': '+358' },
	{ 'cn': 'France', 'cc': 'FR', 'dc': '+33' },
	{ 'cn': 'French Polynesia', 'cc': 'PF', 'dc': '+689' },
	{ 'cn': 'Gabon', 'cc': 'GA', 'dc': '+241' },
	{ 'cn': 'Gambia', 'cc': 'GM', 'dc': '+220' },
	{ 'cn': 'Georgia', 'cc': 'GE', 'dc': '+995' },
	{ 'cn': 'Germany', 'cc': 'DE', 'dc': '+49' },
	{ 'cn': 'Ghana', 'cc': 'GH', 'dc': '+233' },
	{ 'cn': 'Gibraltar', 'cc': 'GI', 'dc': '+350' },
	{ 'cn': 'Greece', 'cc': 'GR', 'dc': '+30' },
	{ 'cn': 'Greenland', 'cc': 'GL', 'dc': '+299' },
	{ 'cn': 'Grenada', 'cc': 'GD', 'dc': '+1' },
	{ 'cn': 'Guam', 'cc': 'GU', 'dc': '+1' },
	{ 'cn': 'Guatemala', 'cc': 'GT', 'dc': '+502' },
	{ 'cn': 'Guernsey', 'cc': 'GG', 'dc': '+44' },
	{ 'cn': 'Guinea', 'cc': 'GN', 'dc': '+224' },
	{ 'cn': 'Guinea-Bissau', 'cc': 'GW', 'dc': '+245' },
	{ 'cn': 'Guyana', 'cc': 'GY', 'dc': '+592' },
	{ 'cn': 'Haiti', 'cc': 'HT', 'dc': '+509' },
	{ 'cn': 'Honduras', 'cc': 'HN', 'dc': '+504' },
	{ 'cn': 'Hong Kong', 'cc': 'HK', 'dc': '+852' },
	{ 'cn': 'Hungary', 'cc': 'HU', 'dc': '+36' },
	{ 'cn': 'Iceland', 'cc': 'IS', 'dc': '+354' },
	{ 'cn': 'India', 'cc': 'IN', 'dc': '+91' },
	{ 'cn': 'Indonesia', 'cc': 'ID', 'dc': '+62' },
	{ 'cn': 'Iran', 'cc': 'IR', 'dc': '+98' },
	{ 'cn': 'Iraq', 'cc': 'IQ', 'dc': '+964' },
	{ 'cn': 'Ireland', 'cc': 'IE', 'dc': '+353' },
	{ 'cn': 'Isle of Man', 'cc': 'IM', 'dc': '+44' },
	{ 'cn': 'Israel', 'cc': 'IL', 'dc': '+972' },
	{ 'cn': 'Italy', 'cc': 'IT', 'dc': '+39' },
	{ 'cn': 'Ivory Coast', 'cc': 'CI', 'dc': '+225' },
	{ 'cn': 'Jamaica', 'cc': 'JM', 'dc': '+1' },
	{ 'cn': 'Japan', 'cc': 'JP', 'dc': '+81' },
	{ 'cn': 'Jersey', 'cc': 'JE', 'dc': '+44' },
	{ 'cn': 'Jordan', 'cc': 'JO', 'dc': '+962' },
	{ 'cn': 'Kazakhstan', 'cc': 'KZ', 'dc': '+7' },
	{ 'cn': 'Kenya', 'cc': 'KE', 'dc': '+254' },
	{ 'cn': 'Kiribati', 'cc': 'KI', 'dc': '+686' },
	{ 'cn': 'Kosovo', 'cc': 'XK', 'dc': '+383' },
	{ 'cn': 'Kuwait', 'cc': 'KW', 'dc': '+965' },
	{ 'cn': 'Kyrgyzstan', 'cc': 'KG', 'dc': '+996' },
	{ 'cn': 'Laos', 'cc': 'LA', 'dc': '+856' },
	{ 'cn': 'Latvia', 'cc': 'LV', 'dc': '+371' },
	{ 'cn': 'Lebanon', 'cc': 'LB', 'dc': '+961' },
	{ 'cn': 'Lesotho', 'cc': 'LS', 'dc': '+266' },
	{ 'cn': 'Liberia', 'cc': 'LR', 'dc': '+231' },
	{ 'cn': 'Libya', 'cc': 'LY', 'dc': '+218' },
	{ 'cn': 'Liechtenstein', 'cc': 'LI', 'dc': '+423' },
	{ 'cn': 'Lithuania', 'cc': 'LT', 'dc': '+370' },
	{ 'cn': 'Luxembourg', 'cc': 'LU', 'dc': '+352' },
	{ 'cn': 'Macau', 'cc': 'MO', 'dc': '+853' },
	{ 'cn': 'Macedonia', 'cc': 'MK', 'dc': '+389' },
	{ 'cn': 'Madagascar', 'cc': 'MG', 'dc': '+261' },
	{ 'cn': 'Malawi', 'cc': 'MW', 'dc': '+265' },
	{ 'cn': 'Malaysia', 'cc': 'MY', 'dc': '+60' },
	{ 'cn': 'Maldives', 'cc': 'MV', 'dc': '+960' },
	{ 'cn': 'Mali', 'cc': 'ML', 'dc': '+223' },
	{ 'cn': 'Malta', 'cc': 'MT', 'dc': '+356' },
	{ 'cn': 'Marshall Islands', 'cc': 'MH', 'dc': '+692' },
	{ 'cn': 'Mauritania', 'cc': 'MR', 'dc': '+222' },
	{ 'cn': 'Mauritius', 'cc': 'MU', 'dc': '+230' },
	{ 'cn': 'Mayotte', 'cc': 'YT', 'dc': '+262' },
	{ 'cn': 'Mexico', 'cc': 'MX', 'dc': '+52' },
	{ 'cn': 'Micronesia', 'cc': 'FM', 'dc': '+691' },
	{ 'cn': 'Moldova', 'cc': 'MD', 'dc': '+373' },
	{ 'cn': 'Monaco', 'cc': 'MC', 'dc': '+377' },
	{ 'cn': 'Mongolia', 'cc': 'MN', 'dc': '+976' },
	{ 'cn': 'Montenegro', 'cc': 'ME', 'dc': '+382' },
	{ 'cn': 'Montserrat', 'cc': 'MS', 'dc': '+1' },
	{ 'cn': 'Morocco', 'cc': 'MA', 'dc': '+212' },
	{ 'cn': 'Mozambique', 'cc': 'MZ', 'dc': '+258' },
	{ 'cn': 'Myanmar', 'cc': 'MM', 'dc': '+95' },
	{ 'cn': 'Namibia', 'cc': 'NA', 'dc': '+264' },
	{ 'cn': 'Nauru', 'cc': 'NR', 'dc': '+674' },
	{ 'cn': 'Nepal', 'cc': 'NP', 'dc': '+977' },
	{ 'cn': 'Netherlands', 'cc': 'NL', 'dc': '+31' },
	{ 'cn': 'Netherlands Antilles', 'cc': 'AN', 'dc': '+599' },
	{ 'cn': 'New Caledonia', 'cc': 'NC', 'dc': '+687' },
	{ 'cn': 'New Zealand', 'cc': 'NZ', 'dc': '+64' },
	{ 'cn': 'Nicaragua', 'cc': 'NI', 'dc': '+505' },
	{ 'cn': 'Niger', 'cc': 'NE', 'dc': '+227' },
	{ 'cn': 'Nigeria', 'cc': 'NG', 'dc': '+234' },
	{ 'cn': 'Niue', 'cc': 'NU', 'dc': '+683' },
	{ 'cn': 'North Korea', 'cc': 'KP', 'dc': '+850' },
	{ 'cn': 'Northern Mariana Islands', 'cc': 'MP', 'dc': '+1' },
	{ 'cn': 'Norway', 'cc': 'NO', 'dc': '+47' },
	{ 'cn': 'Oman', 'cc': 'OM', 'dc': '+968' },
	{ 'cn': 'Pakistan', 'cc': 'PK', 'dc': '+92' },
	{ 'cn': 'Palau', 'cc': 'PW', 'dc': '+680' },
	{ 'cn': 'Palestine', 'cc': 'PS', 'dc': '+970' },
	{ 'cn': 'Panama', 'cc': 'PA', 'dc': '+507' },
	{ 'cn': 'Papua New Guinea', 'cc': 'PG', 'dc': '+675' },
	{ 'cn': 'Paraguay', 'cc': 'PY', 'dc': '+595' },
	{ 'cn': 'Peru', 'cc': 'PE', 'dc': '+51' },
	{ 'cn': 'Philippines', 'cc': 'PH', 'dc': '+63' },
	{ 'cn': 'Pitcairn', 'cc': 'PN', 'dc': '+64' },
	{ 'cn': 'Poland', 'cc': 'PL', 'dc': '+48' },
	{ 'cn': 'Portugal', 'cc': 'PT', 'dc': '+351' },
	{ 'cn': 'Puerto Rico', 'cc': 'PR', 'dc': '+1' },
	{ 'cn': 'Qatar', 'cc': 'QA', 'dc': '+974' },
	{ 'cn': 'Republic of the Congo', 'cc': 'CG', 'dc': '+242' },
	{ 'cn': 'Reunion', 'cc': 'RE', 'dc': '+262' },
	{ 'cn': 'Romania', 'cc': 'RO', 'dc': '+40' },
	{ 'cn': 'Russia', 'cc': 'RU', 'dc': '+7' },
	{ 'cn': 'Rwanda', 'cc': 'RW', 'dc': '+250' },
	{ 'cn': 'Saint Barthelemy', 'cc': 'BL', 'dc': '+590' },
	{ 'cn': 'Saint Helena', 'cc': 'SH', 'dc': '+290' },
	{ 'cn': 'Saint Kitts and Nevis', 'cc': 'KN', 'dc': '+1' },
	{ 'cn': 'Saint Lucia', 'cc': 'LC', 'dc': '+1' },
	{ 'cn': 'Saint Martin', 'cc': 'MF', 'dc': '+590' },
	{ 'cn': 'Saint Pierre and Miquelon', 'cc': 'PM', 'dc': '+508' },
	{ 'cn': 'Saint Vincent and the Grenadines', 'cc': 'VC', 'dc': '+1' },
	{ 'cn': 'Samoa', 'cc': 'WS', 'dc': '+685' },
	{ 'cn': 'San Marino', 'cc': 'SM', 'dc': '+378' },
	{ 'cn': 'Sao Tome and Principe', 'cc': 'ST', 'dc': '+239' },
	{ 'cn': 'Saudi Arabia', 'cc': 'SA', 'dc': '+966' },
	{ 'cn': 'Senegal', 'cc': 'SN', 'dc': '+221' },
	{ 'cn': 'Serbia', 'cc': 'RS', 'dc': '+381' },
	{ 'cn': 'Seychelles', 'cc': 'SC', 'dc': '+248' },
	{ 'cn': 'Sierra Leone', 'cc': 'SL', 'dc': '+232' },
	{ 'cn': 'Singapore', 'cc': 'SG', 'dc': '+65' },
	{ 'cn': 'Sint Maarten', 'cc': 'SX', 'dc': '+1' },
	{ 'cn': 'Slovakia', 'cc': 'SK', 'dc': '+421' },
	{ 'cn': 'Slovenia', 'cc': 'SI', 'dc': '+386' },
	{ 'cn': 'Solomon Islands', 'cc': 'SB', 'dc': '+677' },
	{ 'cn': 'Somalia', 'cc': 'SO', 'dc': '+252' },
	{ 'cn': 'South Africa', 'cc': 'ZA', 'dc': '+27' },
	{ 'cn': 'South Korea', 'cc': 'KR', 'dc': '+82' },
	{ 'cn': 'South Sudan', 'cc': 'SS', 'dc': '+211' },
	{ 'cn': 'Spain', 'cc': 'ES', 'dc': '+34' },
	{ 'cn': 'Sri Lanka', 'cc': 'LK', 'dc': '+94' },
	{ 'cn': 'Sudan', 'cc': 'SD', 'dc': '+249' },
	{ 'cn': 'Suriname', 'cc': 'SR', 'dc': '+597' },
	{ 'cn': 'Svalbard and Jan Mayen', 'cc': 'SJ', 'dc': '+47' },
	{ 'cn': 'Swaziland', 'cc': 'SZ', 'dc': '+268' },
	{ 'cn': 'Sweden', 'cc': 'SE', 'dc': '+46' },
	{ 'cn': 'Switzerland', 'cc': 'CH', 'dc': '+41' },
	{ 'cn': 'Syria', 'cc': 'SY', 'dc': '+963' },
	{ 'cn': 'Taiwan', 'cc': 'TW', 'dc': '+886' },
	{ 'cn': 'Tajikistan', 'cc': 'TJ', 'dc': '+992' },
	{ 'cn': 'Tanzania', 'cc': 'TZ', 'dc': '+255' },
	{ 'cn': 'Thailand', 'cc': 'TH', 'dc': '+66' },
	{ 'cn': 'Togo', 'cc': 'TG', 'dc': '+228' },
	{ 'cn': 'Tokelau', 'cc': 'TK', 'dc': '+690' },
	{ 'cn': 'Tonga', 'cc': 'TO', 'dc': '+676' },
	{ 'cn': 'Trinidad and Tobago', 'cc': 'TT', 'dc': '+1' },
	{ 'cn': 'Tunisia', 'cc': 'TN', 'dc': '+216' },
	{ 'cn': 'Turkey', 'cc': 'TR', 'dc': '+90' },
	{ 'cn': 'Turkmenistan', 'cc': 'TM', 'dc': '+993' },
	{ 'cn': 'Turks and Caicos Islands', 'cc': 'TC', 'dc': '+1' },
	{ 'cn': 'Tuvalu', 'cc': 'TV', 'dc': '+688' },
	{ 'cn': 'U.S. Virgin Islands', 'cc': 'VI', 'dc': '+1' },
	{ 'cn': 'Uganda', 'cc': 'UG', 'dc': '+256' },
	{ 'cn': 'Ukraine', 'cc': 'UA', 'dc': '+380' },
	{ 'cn': 'United Arab Emirates', 'cc': 'AE', 'dc': '+971' },
	{ 'cn': 'United Kingdom', 'cc': 'GB', 'dc': '+44' },
	{ 'cn': 'United States', 'cc': 'US', 'dc': '+1' },
	{ 'cn': 'Uruguay', 'cc': 'UY', 'dc': '+598' },
	{ 'cn': 'Uzbekistan', 'cc': 'UZ', 'dc': '+998' },
	{ 'cn': 'Vanuatu', 'cc': 'VU', 'dc': '+678' },
	{ 'cn': 'Vatican', 'cc': 'VA', 'dc': '+379' },
	{ 'cn': 'Venezuela', 'cc': 'VE', 'dc': '+58' },
	{ 'cn': 'Vietnam', 'cc': 'VN', 'dc': '+84' },
	{ 'cn': 'Wallis and Futuna', 'cc': 'WF', 'dc': '+681' },
	{ 'cn': 'Western Sahara', 'cc': 'EH', 'dc': '+212' },
	{ 'cn': 'Yemen', 'cc': 'YE', 'dc': '+967' },
	{ 'cn': 'Zambia', 'cc': 'ZM', 'dc': '+260' },
	{ 'cn': 'Zimbabwe', 'cc': 'ZW', 'dc': '+263' }
]
